/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

/**
 *
 * @author ORuairc
 */
public class Calculators extends javax.swing.JFrame {

        Double firstNum = 0.0;
        Double secondNum = 0.0;
        Double result = 0.0;
        String operations;
    /**
     * Creates new form Calculators
     */
    public Calculators() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonSub = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonPoint = new javax.swing.JButton();
        jButtonPlusEqual = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 312, 60));

        jButton1.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 61));

        jButton2.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 70, 61));

        jButton3.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 61));

        jButtonSub.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonSub.setText("-");
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 70, 61));

        jButton4.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 61));

        jButton5.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 70, 61));

        jButton6.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 70, 61));

        jButtonAdd.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 70, 61));

        jButton7.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, 61));

        jButton8.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, 61));

        jButton9.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 70, 61));

        jButtonMult.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonMult.setText("*");
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 70, 61));

        jButton0.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 70, 61));

        jButtonPoint.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonPoint.setText(".");
        jButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPointActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 70, 61));

        jButtonPlusEqual.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonPlusEqual.setText("+/- ");
        jButtonPlusEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlusEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 70, 61));

        jButtonEqual.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 70, 61));

        jButtonDel.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonDel.setText("<-");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 61));

        jButtonC.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, 61));

        jButtonDiv.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 70, 61));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //ALL BUTTON ACTIONS
    
    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        
        firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        operations = "*";
        
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String enterNumber = jTextField1.getText();
        //Simply enabling button to enter desired number
        //SAME FOR ALL NUMBER BUTTONS
        if(enterNumber == ""){
            
            jTextField1.setText(jButton4.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton4.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton7.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton7.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton1.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton1.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton2.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton2.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton3.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton3.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        //Getting first number and setting operation to what is on button
        //SAME FOR ALL OPERATION BUTTONS
        firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        operations = "-";
        
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton5.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton5.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton6.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton6.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        
        firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        operations = "+";  
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton8.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton8.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton9.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton9.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        
        String enterNumber = jTextField1.getText();
        
        if(enterNumber == ""){
            
            jTextField1.setText(jButton0.getText());
            
        }
        else{
            
            enterNumber = jTextField1.getText() + jButton0.getText();
            jTextField1.setText(enterNumber);
            
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPointActionPerformed
        
        if(! jTextField1.getText().contains(".")){
            
            jTextField1.setText(jTextField1.getText() + jButtonPoint.getText());
        }
    }//GEN-LAST:event_jButtonPointActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        //For all the Operations on the calculator
        
        String ans;
        secondNum = Double.parseDouble(jTextField1.getText());
        
        if(operations == "+"){
            result = firstNum + secondNum;
            ans = String.format("%.2f", result);
            jTextField1.setText(ans);
            
        }
        else if(operations == "-"){
            result = firstNum - secondNum;
            ans = String.format("%.2f", result);
            jTextField1.setText(ans);
        }
        else if(operations == "*"){
            result = firstNum * secondNum;
            ans = String.format("%.2f", result);
            jTextField1.setText(ans);
        }
        else if(operations == "/"){
            result = firstNum / secondNum;
            ans = String.format("%.2f", result);
            jTextField1.setText(ans);
        }
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonPlusEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusEqualActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = ops * (-1);
        jTextField1.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_jButtonPlusEqualActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        //Deleting lastest number entered if it is a mistake
        String backspace = null;
        
        if(jTextField1.getText().length() > 0){
            
            StringBuilder strB = new StringBuilder(jTextField1.getText());
            strB.deleteCharAt(jTextField1.getText().length() - 1);
            backspace = strB.toString();
            jTextField1.setText(backspace);
        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        
        firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        operations = "/";
    }//GEN-LAST:event_jButtonDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonPlusEqual;
    private javax.swing.JButton jButtonPoint;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
