//
//  main.cpp
//  AS
//
//  Created by Céin O'Rourke on 02/10/2017.
//  Copyright © 2017 Céin O'Rourke. All rights reserved.
//

#include <iostream>
#include <string>
using namespace std;

class Vigenere
{
public:
    string key;
    
    Vigenere(string key)
    {
        for(int i = 0; i < key.size(); ++i)
        {
            if(key[i] >= 'A' && key[i] <= 'Z')
                this->key += key[i];
            else if(key[i] >= 'a' && key[i] <= 'z')
                this->key += key[i] + 'A' - 'a';
        }
    }
    
    
    string decrypt(string text)
    {
        string out;
        
        for(int i = 0, j = 0; i < text.length(); ++i)
        {
            char c = text[i];
            
            if(c >= 'a' && c <= 'z')
                c += 'A' - 'a';
            else if(c < 'A' || c > 'Z')
                continue;
            
            out += (c - key[j] + 26) % 26 + 'A';
            j = (j + 1) % key.length();
        }
        
        return out;
    }
};

int main()
{
    Vigenere cipher("KISWAHILI");
    
    string original = "XQKPIZIMWEBLKAUVZCXKWPHLVPERIKDASOZZSBZITOIEESTDXEJWXMCPSPHPATADPWNEZCWBYNSOIEGPIBKGIPLBTBSWFWNKUJWGVKGEPVTAYVWKFAPPNSDWNETITVSVYBIUIWQCBKKUAWQIXQFETPIWQDAHNOIIMTIBGKLHBPNYZEATVIQNOKLPHLNTVKTVACPATWXJMPIHUSWZQFCFVZYWKESNDPBDVYBLDAABSMXMODAZPQCXKLEOUALZOVLWNFOZWNQLOTOIEEOLGJTYMLTVGFAEKWYMGPWJWLAEIBBWZTOQDXBWUASZJLKUQFETSWZSOLSOIMEPEYCDZBLVPMNQFCAUMHPKAZBUUKEQYVKKOUBSMCPSBATQWGGPAYHPACMKTDUPHZEWPBZAMKIYLWLXWMPTJEKAMJDLZTVMZWWSPVRXBMKOUYMQZYUFAWAGAMCWXYRFXEIXIDUSPAHMNQVJTRVZERWOHOUOEPODSNIVCDARINWRPIYBCEGQLKZPUKQFOEJCCMLCLETZIYLCPSESZBTTVTGKKPVROYWVAVLVHWBAWJOUMZNDPWOHHKLVNQVWTLATACQYJIMQNIXBDUBLBEMBAGIEHZPNKALARICEVYBGNDLZDWPUSCNPBFLONSOTLZDWWMSNEZULTVMJENOICLGIJABBBYWDWJZEYAZNWIYJIACOMCUSHLLZHPOVKDAPALVXWMJCLLTUQWAJGAWCMMWEIEULEPKBMJLLADBRMAIPYWGMWMFPSHZPKBQLECHTEWDPWERHXATSKSPIVVAMYXDASAQNSGQLDTOMEZSMVWNKBCCOAZWAATPICBXKRHESQVMAZOUBEPSVCJIZBTAQWAJGAWLVXWMJCLVZIGIJZIAPTVUQLOGVQYODWHECRWYMKVVKFAPPNSDWNETITVSVYEDVVEZOIDHYOIGMKNSROYQEMYNUKUYAPQGIFPSRMTVDWOENICEBRILOOBBZNZMJOOUIWXBQVANVBQWBAGIEVJUMMBAREYMLAYVSJDDPTTOQDEKLAZUOUGNEAPLVYBZARZQEPSVCWNFEZCVLTAORIJEOTDIAFJPBRMJASVVPZOIKKNUQDBCPGQLKKSWYAWOKLQYAUMAJIZVEREALWHHASNEVUPIVVTBCBZALHZRMLTGYKJQAPOZLDRLMQQCPSJDHUPKRIFESTBZBEZFETPVEWKPSOHMCYKDQGJIAPTVUBZAWVZWLKKLQASTJVOMVOASICOOJDKCRKTXRMJWNKQQVSALYHVWDMCACAIUEPTVOWPOUM";
    
    string decrypted = cipher.decrypt(original);
    
    cout << original << endl;
    
    cout << "Decrypted: " << decrypted << endl;
}
